name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Login to DockerHub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Pull Docker Image
      run: docker pull hsr077/react-app:1.0

    - name: SSH and Deploy
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: 204.236.223.246
        username: ${{ secrets.EC2_USER }}
        key: ${{ secrets.EC2_SSH_KEY }}
        port: 22
        script: |
          sudo docker stop myapp || true
          sudo docker rm myapp || true
          sudo docker pull hsr077/react-app:1.0
          sudo docker run -d \
            -p 80:80 \
            --restart always \
            --name myapp \
            hsr077/react-app:1.0
